language: php

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

matrix:
  allow_failures:
    - php: 7.2
    - php: 7.3
    - php: 7.4

before_script:
  - composer self-update
  - touch storage/database.sqlite
  - touch storage/testing.sqlite
  - cp .env.example .env
  - composer install -n --prefer-dist
  - php artisan migrate --database=testing --force
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run
